-- Seed: 42 sites from FE_OM_Dashboard_2026.html SEED_SITES
-- Only inserts if the sites table is empty to avoid overwriting live data

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM sites) = 0 THEN

    INSERT INTO sites (id, data) VALUES
    ('26024', '{"name":"Motus","location":"Mbombela, Mpumalanga","capacity_kwp":"57.60","modules":96,"contractor":"Exosolar","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":null,"annual_sla":null,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"2 cln","Jun":"","Jul":"","Aug":"3 cln","Sep":"","Oct":"","Nov":"4 cln 1 Inps","Dec":""}}'),
    ('26007', '{"name":"Rynfield","location":"Benoni, JHB","capacity_kwp":"80.59","modules":140,"contractor":"Solar Panel Cleaners","cleans_per_year":3,"partial_inspections":3,"annual_inspection":1,"monthly_income":1795.74,"annual_sla":21548.88,"annual_cost":15180,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"3 cln 1 Insp","Oct":"","Nov":"","Dec":""}}'),
    ('26008', '{"name":"Randpark","location":"Randburg, JHB","capacity_kwp":"96.6","modules":168,"contractor":"Solar Panel Cleaners","cleans_per_year":3,"partial_inspections":3,"annual_inspection":1,"monthly_income":1885.9,"annual_sla":22630.8,"annual_cost":15180,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"3 cln 1 Insp","Oct":"","Nov":"","Dec":""}}'),
    ('26012', '{"name":"Raslouw","location":"Centurion, Tshwane","capacity_kwp":"172.80","modules":300,"contractor":"Solar Panel Cleaners","cleans_per_year":3,"partial_inspections":3,"annual_inspection":1,"monthly_income":2722.3,"annual_sla":32667.6,"annual_cost":15180,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"","Oct":"3 cln 1 Insp","Nov":"","Dec":""}}'),
    ('26011', '{"name":"Pecanwood","location":"Hartbeespoort, North West","capacity_kwp":"149.76","modules":260,"contractor":"Solar Panel Cleaners","cleans_per_year":3,"partial_inspections":3,"annual_inspection":1,"monthly_income":4530.37,"annual_sla":54364.44,"annual_cost":25668,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"","Oct":"3 cln 1 Insp","Nov":"","Dec":""}}'),
    ('26013', '{"name":"Southdowns","location":"Centurion, Tshwane","capacity_kwp":"369.58","modules":642,"contractor":"Solar Panel Cleaners","cleans_per_year":3,"partial_inspections":3,"annual_inspection":1,"monthly_income":5912.86,"annual_sla":70954.32,"annual_cost":21044.66,"lat":null,"lng":null,"months":{"Jan":"","Feb":"1 cln","Mar":"","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"","Oct":"3 cln 1 Insp","Nov":"","Dec":""}}'),
    ('26025', '{"name":"Kyalami","location":"Kyalami, Midrand","capacity_kwp":"103.50","modules":180,"contractor":"Solar Panel Cleaners","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":2575,"annual_sla":30900,"annual_cost":27600,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"1 cln","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"3 cln 1 Insp","Oct":"","Nov":"","Dec":"4 cln"}}'),
    ('26026', '{"name":"Lonehill Prep","location":"Sandton, JHB","capacity_kwp":"73.60","modules":128,"contractor":"Solar Panel Cleaners","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":2550,"annual_sla":30600,"annual_cost":18975,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"1 cln","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"3 cln 1 Insp","Oct":"","Nov":"","Dec":"4 cln"}}'),
    ('26027', '{"name":"Mooikloof","location":"Pretoria, Tshwane","capacity_kwp":"73.81","modules":122,"contractor":"Solar Panel Cleaners","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":1740,"annual_sla":20880,"annual_cost":18975,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln","May":"","Jun":"","Jul":"2 cln","Aug":"","Sep":"","Oct":"3 cln 1 Insp","Nov":"","Dec":"4 cln"}}'),
    ('24267', '{"name":"Curro Magic Beings","location":"Randburg, JHB","capacity_kwp":63,"modules":114,"contractor":"Solar Panel Cleaners","cleans_per_year":1,"partial_inspections":1,"annual_inspection":1,"monthly_income":2010,"annual_sla":24120,"annual_cost":11040,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln","May":"","Jun":"","Jul":"","Aug":"1 Inps","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24263', '{"name":"Irvines Africa TwelveB","location":"Sandton, JHB","capacity_kwp":60,"modules":104,"contractor":"Solar Panel Cleaners","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('26028', '{"name":"Fourways","location":"Sandton, JHB","capacity_kwp":"142.78","modules":236,"contractor":"Solar Panel Cleaners","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":3407,"annual_sla":40884,"annual_cost":11040,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"1 cln","Apr":"","May":"","Jun":"2 cln","Jul":"","Aug":"","Sep":"3 cln 1 Insp","Oct":"","Nov":"","Dec":"4 cln"}}'),
    ('O26003', '{"name":"Carlswald Shopping Centre","location":"Midrand, JHB","capacity_kwp":"987.28","modules":2408,"contractor":"Solar Panel Cleaners","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24232', '{"name":"CFW Assegai","location":"Parow, CPT","capacity_kwp":"217.8","modules":396,"contractor":"Manno Solfield","cleans_per_year":1,"partial_inspections":1,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln 1 F Insp","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24232b', '{"name":"CFW Parin","location":"Parow, CPT","capacity_kwp":"180.95","modules":329,"contractor":"Manno Solfield","cleans_per_year":1,"partial_inspections":1,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln 1 F Insp","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24246', '{"name":"Curro Century City","location":"Century City, CPT","capacity_kwp":"70.95","modules":129,"contractor":"Solar Shine Solutions & FE","cleans_per_year":1,"partial_inspections":1,"annual_inspection":1,"monthly_income":2010,"annual_sla":24120,"annual_cost":2888,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln","May":"","Jun":"","Jul":"","Aug":"1 F Inps","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24248', '{"name":"Curro Langebaan","location":"Langebaan, WCP","capacity_kwp":"90.48","modules":156,"contractor":"Solar Shine Solutions & FE","cleans_per_year":1,"partial_inspections":1,"annual_inspection":1,"monthly_income":2010,"annual_sla":24120,"annual_cost":4274,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"1 cln","May":"","Jun":"","Jul":"","Aug":"","Sep":"1 F Inps","Oct":"","Nov":"","Dec":""}}'),
    ('24264', '{"name":"The New National","location":"Parow, CPT","capacity_kwp":"51.7","modules":94,"contractor":"Solar Shine Solutions & FE","cleans_per_year":2,"partial_inspections":1,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24280', '{"name":"Du Kloof","location":"Paarl, WCP","capacity_kwp":"170.6","modules":282,"contractor":"Solar Shine Solutions & FE","cleans_per_year":2,"partial_inspections":4,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('22024', '{"name":"Soetendal","location":"Wellington, WCP","capacity_kwp":"45.5","modules":100,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('22059', '{"name":"Voorspoed","location":"Wellington, WCP","capacity_kwp":18,"modules":32,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24278', '{"name":"CPOA","location":"Grassy Park, CPT","capacity_kwp":90,"modules":148,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23119', '{"name":"3C Metal","location":"Bellville, CPT","capacity_kwp":361,"modules":656,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23153', '{"name":"Vastech Electron 23","location":"Stellenbosch, WCP","capacity_kwp":114,"modules":248,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23187', '{"name":"Groenvlei","location":"Wellington, WCP","capacity_kwp":374,"modules":676,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23188', '{"name":"CRF","location":"Waterfront, CPT","capacity_kwp":70,"modules":127,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23211', '{"name":"Doornekraal","location":"Malmesbury, WCP","capacity_kwp":77,"modules":140,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23215', '{"name":"Huis Stilbaai","location":"Still Bay, WCP","capacity_kwp":117,"modules":212,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23216', '{"name":"Vastech Photon 5","location":"Stellenbosch, WCP","capacity_kwp":405,"modules":736,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('23220', '{"name":"Fountain Rez","location":"Rondebosch, CPT","capacity_kwp":50,"modules":90,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24238', '{"name":"Herfsvreudge","location":"Bonnievale, WCP","capacity_kwp":41,"modules":74,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24240', '{"name":"Jon Stoffberg","location":"Paarl, WCP","capacity_kwp":45,"modules":82,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24243', '{"name":"Bay Village","location":"Gordon''s Bay, CPT","capacity_kwp":49,"modules":89,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24254', '{"name":"Meshco Blackheath","location":"Blackheath, CPT","capacity_kwp":933,"modules":1608,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24258', '{"name":"Baby Foods Office","location":"Ottery, CPT","capacity_kwp":42,"modules":75,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24259', '{"name":"Baby Foods Factory","location":"Ottery, CPT","capacity_kwp":164,"modules":299,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24274', '{"name":"Laerskool Marble Hall","location":"Marble Hall, LIMPOPO","capacity_kwp":39,"modules":64,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('24285', '{"name":"Parow Business Park Khusela","location":"Parow, CPT","capacity_kwp":46,"modules":74,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('26014', '{"name":"KWV","location":"Paarl, WCP","capacity_kwp":1002,"modules":1630,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('26019', '{"name":"President Hotel","location":"Sea Point, CPT","capacity_kwp":149,"modules":229,"contractor":"Solar Shine Solutions & FE","cleans_per_year":null,"partial_inspections":null,"annual_inspection":null,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}'),
    ('O26001', '{"name":"Harbour Bay Mall","location":"Simon''s Town, WCP","capacity_kwp":484,"modules":1100,"contractor":"Solar Shine Solutions & FE","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":32678.4,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"1 cln 1 F Insp","Apr":"","May":"","Jun":"2 cln Insp","Jul":"","Aug":"","Sep":"2 cln Insp","Oct":"","Nov":"","Dec":"2 cln Insp"}}'),
    ('O26002', '{"name":"The Walk Shopping Centre","location":"Bloemfontein, FS","capacity_kwp":"369.82","modules":902,"contractor":"Solar Panel Cleaners & FE","cleans_per_year":4,"partial_inspections":4,"annual_inspection":1,"monthly_income":null,"annual_sla":0,"annual_cost":null,"lat":null,"lng":null,"months":{"Jan":"","Feb":"","Mar":"","Apr":"","May":"","Jun":"","Jul":"","Aug":"","Sep":"","Oct":"","Nov":"","Dec":""}}');

  END IF;
END $$;
